name: Docker Publish
on:
  push:
    branches:
      - main
jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          registry: ghcr.io
          repository: <username>/<repository-name>
          tags: latest
      - name: Slack good
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_CHANNEL: slack_git
          SLACK_COLOR: 'green'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'good'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: gitAction
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: slack bad
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_CHANNEL: slack_git
          SLACK_COLOR: 'red'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'bad'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: gitAction
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
